### ISSUE TITLE
Deployment Link  For Portfolio Website

### ISSUE THREAD

**Issue by DebyGrey** [DebyGrey/portfolio#10]
Hello, 
you can now use this link to access the portfolio website online: 

[live version](https://debygrey.github.io/portfolio/)

**Comment by wayungi** [comment]
- [ ] Please make ensure to add a link to your live version of the project either in the issues as you have done now or update the `readme` and make a pull request.`[live version](url)`

![link](https://user-images.githubusercontent.com/99656687/230871422-8a6d6f39-651c-403a-bee4-88bc4455b329.png)

**Comment by levy002** [comment]
## Hello @DebyGrey 

Your project is complete!  There is nothing else to say other than... Congratulations! 🎉 


## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] Kindly make sure to update your README and add the LIVE DEMO LINK.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DebyGrey** [comment]
> ## Hello @DebyGrey
> Your project is complete! There is nothing else to say other than... Congratulations! 🎉
> 
> ## Status: APPROVED 🔥 🔥
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> * [OPTIONAL] Kindly make sure to update your README and add the LIVE DEMO LINK.
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you @levy002
