### ISSUE TITLE
Review by morning team session

### ISSUE THREAD

**Issue by hagan199** [DebyGrey/portfolio#8]
No issue yet.

**Comment by hagan199** [comment]
Section tag instead of the div tag because the section element can be used to divide up a web page into standalone sections of related content. Using the section element over a generic container element like div can help make your code more accessible and understandable to search engines, browsers, assistive technologies, and other developers.

**Comment by gergitokusse** [comment]
👍 👍 👍 Almost prefect 👍 👍 👍

**Comment by DebyGrey** [comment]
Thank you guys for your contributions and support! @hagan199 @gergitokusse

**Comment by AleWaweru** [comment]
1.Consider Make the header text more visible for accessibility purposes.
